config/routes.rb
Rails.application.routes.draw do
  get 'subcategories/index'
  get 'categories/index'
  get 'categories/show'
  devise_for :users

  resources :categories
  # resources :subcategories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :set_categories

end


private

def set_categories
  @categories = Category.all
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:subcategories).all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def index
    @subcategories = Subcategory.all
  end

  def show 
  
    @subcategory = Subcategory.find(params[:id])
  end

  def new 
    @subcategory = Subcategory.new
    @categories = Category.all
end
 
 def create
   @subcategory = Subcategory.new(category_params)

   if @subcategory.save
    redirect_to subcategories_path
   else
    render :new, status: :unprocessable_entity
   end 
  end


  def edit
    @subcategory = Subcategory.find(params[:id])
    @categories = Category.all
  end

  def update
    @subcategory = Subcategory.find(params[:id])

    if @subcategory.update(category_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessebly_entity
    end 
  end

  def destroy
    @subcategory = Subcategory.find(params[:id])
    @subcategory.destroy

    redirect_to root_path, status: :see_other
  end



  private
  def category_params
    params.require(:category).permit(:name, :category_id) 
  end


   end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
    
    <div class="form-group">
      <%= form.label :name %> <br>
      <%= form.text_field :name %>
    </div>
  
    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/categories/_nav.html.erb
<header class="bg-dark text-white py-3">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-3">
        <%= link_to root_path, class: "text-white text-decoration-none" do %>
          <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNo7WM9PHyM8ypmyguH-uSWP4xFDP6o5XFUA&s", alt: "Logo", height: 40, class: "rounded-circle" %>
          <span class="ms-2 fs-4">E-commerce App</span>
        <% end %>
      </div>
      <div class="col-md-6">
        <nav class="navbar navbar-expand-lg navbar-dark">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
              
              <% @categories.each do |category| %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="categoryDropdown<%= category.id %>" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= category.name %>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="categoryDropdown<%= category.id %>">
                    <% category.subcategories.each do |subcategory| %>
                      <li><%= link_to subcategory.name, subcategory_path(subcategory), class: "dropdown-item" %></li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
              
              
            </ul>
          </div>
        </nav>
      </div>
      <div class="col-md-3 text-end">
        <% if user_signed_in? %>
          <div class="dropdown">
            <button class="btn btn-outline-warning dropdown-toggle" type="button" id="settingsDropdown" data-bs-toggle="dropdown" aria-expanded="false">
              Settings
            </button>
            <ul class="dropdown-menu" aria-labelledby="settingsDropdown">
              <li><%= link_to 'Create new category', new_category_path, class: "dropdown-item" %></li>
              <li>
                <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "dropdown-item", form: { data: { turbo_confirm: "Are you sure?" } } %>
              </li>
            </ul>
          </div>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, class: "btn btn-outline-light" %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

  </head>

  <body>

<%= render 'categories/nav' %>

    <%= yield %>
      <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/subcategories/_form.html.erb
<%= form_with model: subcategory do |form| %>
    
    <div class="form-group">
      <%= form.label :name %> <br>
      <%= form.text_field :name %>
    </div>

    <div class="form-group">
    <%= form.label :category_id %> <br>
    <%= form.select :category_id, options_from_collection_for_select(@categories, :id, :name)%>
  </div>
  
  
    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/subcategories/edit.html.erb
<%= render 'form', subcategory: @subcategory %>

app/views/subcategories/index.html.erb
<h1>Subcategories#index</h1>
<p>Find me in app/views/subcategories/index.html.erb</p>

app/views/subcategories/new.html.erb
<%= render 'form', subcategory: @subcategory %>